name: "Prod Build: Java App Container"

on:
  pull_request:
    paths: 
      - 'containers/javaapp/**'

jobs:
    build:
        name: "Prod Image Build"
        runs-on: ubuntu-latest
        env:
          environment: prod
          imagetag: "latest"
          containerpath: "containers/javaapp"
          registry: "ghcr.io/${{ github.repository_owner }}"
        permissions: 
          contents: read
          packages: write
          attestations: write
          id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Docker Login
              uses: azure/docker-login@v2
              with:
                login-server: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}                   

            - name: Convert Organization Name to Lowercase
              run: echo "registry_name=$(echo $registry | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV                  

            - name: Build and Tag Image
              id: container-build
              working-directory: ${{ env.containerpath }}
              run: | 
                docker build --target $environment -t ${{ env.registry_name }}/$(basename $containerpath):$imagetag .

            - name: Download TwistCLI
              run: |
                curl -u "${{ secrets.PRISMA_USERNAME }}:${{ secrets.PRISMA_PASSWORD }}" \
                -o twistcli \
                "https://app0.cloud.twistlock.com/app0-93082728/api/v1/util/twistcli"
                chmod +x twistcli

            - name: Scan Docker Image with TwistCLI
              run: |
                ./twistcli images scan \
                  --address "https://app0.cloud.twistlock.com/app0-93082728" \
                  --user ${{ secrets.PRISMA_USERNAME }} \
                  --password ${{ secrets.PRISMA_PASSWORD }} \
                  ${{ env.registry_name }}/$(basename $containerpath):$imagetag

            - name: Push Images to Container Registry
              run: |
                docker push ${{ env.registry_name }}/$(basename $containerpath):$imagetag
